name: GH-Pages Deployment

on: push

jobs:
  GH-Pages-Deployment-Sutanguru:
    name: deploy to sutangu.ru
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v2.5.1
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ALS_UBUNTU_DEPLOY_KEY }}
